site_name: Knowledge Base
site_author: Romeo Mhakayakora
site_url: https://romeo-mhakayakora.github.io/knowledge/
repo_url: https://github.com/romeo-mhakayakora/knowledge
repo_name: romeo-mhakayakora/knowledge
docs_dir: content
site_dir: site
theme:
  name: material
  locale: en
  logo: images/logo.svg
  favicon: images/favicon.ico
  features:
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate
    - navigation.indexes
    - navigation.top
    - navigation.tabs
    - toc.follow
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - search:
      lang: en
      separator: '[\s\-_.]+'
      min_search_length: 3
      prebuild_index: true
      indexing: "full"
  - tags

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      use_pygments: true
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - tables
  - toc:
      permalink: true
  - meta
  - attr_list
  - md_in_html

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - styles/custom.css

nav:
  - Home: index.md
  - Domains:
    - Mathematics: domains/mathematics.md
    - Computer Science: domains/computer-science.md
    - AI: domains/ai.md
    - Economics: domains/economics.md
    - Physics: domains/physics.md
    - Systems: domains/systems.md
    - Business: domains/business.md
  - Search: search/index.md
  - Tags: tags/index.md

copyright: Copyright &copy; 2026 Romeo Mhakayakora
